package anime.anime; 
import java.util.List; 
public class Anime {
    public String request_hash;
    public boolean request_cached;
    public int request_cache_expiry;
    public int mal_id;
    public String url;
    public String image_url;
    public String trailer_url;
    public String title;
    public String title_english;
    public String title_japanese;
    public List<String> title_synonyms;
    public String type;
    public String source;
    public int episodes;
    public String status;
    public boolean airing;
    public Aired aired;
    public String duration;
    public String rating;
    public double score;
    public int scored_by;
    public int rank;
    public int popularity;
    public int members;
    public int favorites;
    public String synopsis;
    public Object background;
    public String premiered;
    public String broadcast;
    public Related related;
    public List<Producer> producers;
    public List<Licensor> licensors;
    public List<Studio> studios;
    public List<Genre> genres;
    public List<Object> explicit_genres;
    public List<Object> demographics;
    public List<Theme> themes;
    public List<String> opening_themes;
    public List<String> ending_themes;
    public List<ExternalLink> external_links;
}
